spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/user/**
            - id: storage-service
              uri: lb://storage-service
              predicates:
                - Path=/api/v1/item/**
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/v1/payment/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/order/**
            - id: delivery-service
              uri: lb://delivery-service
              predicates:
                - Path=/api/v1/delivery/**

management:
  tracing:
    sampling:
      probability: 1.0


server:
  port: 8222