spring:
  application:
    name: storage-service
  datasource:
    url: jdbc:postgresql://localhost:5432/storage
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql

server:
  port: 8020

management:
  tracing:
    sampling:
      probability: 1.0
