spring:
  application:
    name: analytics-service
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: analytics-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.pet.common.dto.kafka

server:
  port: 8060
