spring:
  application:
    name: user-service
  data:
    mongodb:
      database: user
      port: 27017
      username: admin
      password: admin
      host: localhost
      authentication-database: admin
server:
  port: 8030

management:
  tracing:
    sampling:
      probability: 1.0